version: '3.8'

services:
  storage-api:
    image: localhost/tveu/storage/storage-api:0.0.1
    ports:
      - "3000:3000"
    networks:
      - storage-network

networks:
  storage-network:
    driver: bridge
